/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cesion;
import com.itextpdf.text.BaseColor; 
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document; 
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize; 
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase; 
import com.itextpdf.text.pdf.Barcode;
import com.itextpdf.text.pdf.BarcodeEAN; 
import com.itextpdf.text.pdf.PdfContentByte; 
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.*;
import com.itextpdf.text.Paragraph;
import java.io.*; 

import java.util.Calendar;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author dev
 */
public class pos extends javax.swing.JFrame {
DefaultTableModel modelo;
DefaultTableModel modelodet;
    /**
     * Creates new form pos
     */
    public pos() {
        initComponents();
        setLocationRelativeTo(null);
        limpiar();
        
        modelo = new DefaultTableModel();
        jTable2.setModel(modelo);
//ableColumnModel columnModel = tabla.getColumnModel();
   
        modelo.addColumn("Id");
        modelo.addColumn("Codigo");
        modelo.addColumn("Productos");
        modelo.addColumn("$ Venta");
        
       TableColumnModel columnModel = jTable2.getColumnModel();
       columnModel.getColumn(0).setWidth(0);
       columnModel.getColumn(0).setMinWidth(0);
       columnModel.getColumn(0).setMaxWidth(0);
       columnModel.getColumn(1).setWidth(0);
       columnModel.getColumn(1).setMinWidth(0);
       columnModel.getColumn(1).setMaxWidth(0);
       columnModel.getColumn(2).setWidth(300); 
        columnModel.getColumn(2).setMinWidth(300);
       columnModel.getColumn(2).setMaxWidth(300);
      
        modelodet = new DefaultTableModel();
        jTable1.setModel(modelodet);
        
       
        modelodet.addColumn("Codigo");
        modelodet.addColumn("Productos");
        modelodet.addColumn("Un");
        modelodet.addColumn("Cantidad");
        modelodet.addColumn("$ Precio");
        modelodet.addColumn("Total");
        
    TableColumnModel columnModel2 = jTable1.getColumnModel();
       columnModel2.getColumn(0).setPreferredWidth(100);
       columnModel2.getColumn(1).setPreferredWidth(300);
       columnModel2.getColumn(2).setPreferredWidth(50); 
       columnModel2.getColumn(3).setPreferredWidth(100);
       columnModel2.getColumn(4).setPreferredWidth(100);
       columnModel2.getColumn(5).setPreferredWidth(100);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setTitle("Punto de Venta");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Total");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("jTextField4");

        jLabel5.setText("Pago");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("jTextField5");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jLabel6.setText("Vuelto");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("jTextField6");

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("usuario->");

        jLabel1.setText("Codigo");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jLabel2.setText("Producto");

        jLabel3.setText("Cantidad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("..");

        jButton3.setText("..");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("..");

        jButton6.setText("Factura FV");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Guia GD");

        jLabel8.setText("Rut");

        jTextField7.setText("jTextField7");
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jLabel9.setText("Razon");

        jTextField8.setText("jTextField8");

        jLabel10.setText("Direccion");

        jTextField9.setText("jTextField9");

        jLabel11.setText("Comuna");

        jTextField10.setText("jTextField10");

        jLabel13.setText("Ciudad");

        jTextField11.setText("jTextField11");

        jLabel14.setText("Giro");

        jTextField12.setText("jTextField12");

        jButton8.setText("Nuevo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(376, 376, 376)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton6)
                        .addGap(28, 28, 28)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton3)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addGap(5, 5, 5))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton8))
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDriver() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
    }catch(Exception ex) {

    }
  }
    private void limpiarjtable(){
    modelo.setRowCount(0);
    modelodet.setRowCount(0);
   }
    
    public void buscarcli(){
       
       
        String Buscar= jTextField7.getText();
        cargarDriver();
        String dbURL = "jdbc:mysql://localhost:3306/ferreteria2"; 
        String username ="root"; 
        String password = "NSloteria2015"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select rut,nombre,direccion,comuna,ciudad,giro from clientes where rut = '"+Buscar+"'"; 
        //  JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
          
        jTextField8.setText(rs.getString(2));
        jTextField9.setText(rs.getString(3)); 
        jTextField10.setText(rs.getString(4)); 
        jTextField11.setText(rs.getString(5)); 
        jTextField12.setText(rs.getString(6));
       
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

    }
    
    public void llenar1(){
       
       
        String Buscar= jTextField2.getText();
        cargarDriver();
        String dbURL = "jdbc:mysql://localhost:3306/ferreteria2"; 
        String username ="root"; 
        String password = "NSloteria2015"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select id,codigo,producto,venta from productos where producto like '%"+Buscar+"%'"; 
         // JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
              
              Object []object = new Object[4];
        object[0] = rs.getString(1);
        object[1] = rs.getString(2); 
        object[2] = rs.getString(3); 
        object[3] = rs.getString(4); 
  System.out.println("Si" );
        
        modelo.addRow(object);
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

    }

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
 DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        // get the selected row index
       int selectedRowIndex = jTable2.getSelectedRow();
        
          Object []object = new Object[6];
        object[0] =  model.getValueAt(selectedRowIndex, 1).toString();
        object[1] =  model.getValueAt(selectedRowIndex, 2).toString();
        object[2] =   "";
        object[3] =  "1";
         object[4] =    model.getValueAt(selectedRowIndex, 3).toString();
          object[5] =    model.getValueAt(selectedRowIndex, 3).toString();
  System.out.println("Si" );
        
        modelodet.addRow(object);
        jTextField2.setText("");
  jTextField2.grabFocus();
  sumardet();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         limpiarjtable();
        // TODO add your handling code here:
  llenar1();
  jTextField2.setText("");
  jTextField2.grabFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    void difpago(){
        String cad1=jTextField4.getText().trim();
            String cad2=jTextField5.getText().trim();
            int x1=Integer.parseInt(cad1);
            int x2=Integer.parseInt(cad2);
            int suma=x2-x1;
            String total=String.valueOf(suma);  
            jTextField6.setText(total);
    }
    void sumardet(){
        double sumatoria1=0;
        int totalRow= jTable1.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
             double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,5)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando
             sumatoria1+=sumatoria;
 
          System.out.println(""+sumatoria1);
 
           }
        int numero = (int)sumatoria1;
 jTextField4.setText(String.valueOf((numero)));
}

void imprimirpdf(){
    String pdfFile="C:\\dte3\\doc33.pdf";
    
     Document document = new Document();
      
    try {
        Image imagen = Image.getInstance("pdf417.png");  
      PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(pdfFile));
      document.open();
      PdfContentByte cb = writer.getDirectContent();

      cb.beginText();

      BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
      cb.setFontAndSize(bf, 14);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Empresa", 50, 800, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Direccion", 50, 780, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Comuna", 50, 760, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Ciudad", 50, 740, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "email", 50, 720, 0);
      
       cb.setFontAndSize(bf, 9);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Razon", 50, 680, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Rut", 350, 680, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Direccion", 50, 660, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Fecha", 350, 660, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Comuna", 50, 640, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Forma de Pago", 350, 640, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Ciudad", 50, 620, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Telefono", 50, 600, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "email", 50, 580, 0);
       
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Codigo", 50, 550, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Producto", 100, 550, 0);
         cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Unidad", 250, 550, 0);
          cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "$ Precio", 300, 550, 0);
           cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Cantidad", 400, 550, 0);
            cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Total", 500, 550, 0);
       
       
       
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Subtotal", 400, 180, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Descuento", 400, 160, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Neto", 400, 140, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Iva (19%)", 400, 120, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Total", 400, 100, 0);
     
      
      
       
       
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Timbre Electronico SII", 150, 100, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Resolucion 0 de 2014", 150, 90, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Verifique documento:www.sii.cl", 130, 80, 0);
       cb.setColorFill(BaseColor.RED);
       cb.setFontAndSize(bf, 10);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "SII.-SANTIAGO CENTRO", 430, 700, 0);
         cb.setFontAndSize(bf, 14);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "RUT.:",420, 780, 0);
         cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "FACTURA ELECTRONICA", 400, 760, 0);
          cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Nª", 450, 740, 0);
      cb.endText();
      
       imagen.setAbsolutePosition(25, 130);
        document.add(imagen);
        
       cb.setRGBColorFill(255, 51, 51);
       cb.setLineWidth(2);
       //x eje y ancho alto
       cb.rectangle(380,710,200,100);
       cb.stroke();
       
       
       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,10,580,820);
       cb.stroke();

       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,540,580,25);
       cb.stroke();
       
       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,540,580,150);
       cb.stroke();
   
  

    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
    document.close();
  
    try {
                Desktop.getDesktop().open(new File("C:\\dte3\\doc33.pdf"));
                //To check if the solution is open or not, you can wait some time here
                Thread.sleep(1000);

            } catch (IOException | InterruptedException ex) {
             //   Logger.getLogger(Open.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
 


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(jTable1.getSelectedRow()); 
        sumardet();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        cargarDriver();
        String dbURL = "jdbc:mysql://localhost:3306/ferreteria2"; 
        String username ="root"; 
        String password = "NSloteria2015"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        int es=0;
        //buscar numero boleta
      String query1 ="select documento,contador from contador where documento='BOL'"; 
         // JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query1); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query1);  
           while(rs.next()){ 
              
           
         es = rs.getInt(2)+1;
       
 
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }
    
        //fin buscar numero boleta
        
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);
        //JOptionPane.showMessageDialog(null, "insert into boletas(numero_bol,total,fecha,hora) values ("+String.valueOf(es)+"","+jTextField4.getText()+",'"+sqlDate.toString()+"','"+sqlTime+"')");
          try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          comando.executeUpdate("insert into boletas(estado,numero_bol,total,fecha,hora) values ('VIGENTE',"+String.valueOf(es)+","+jTextField4.getText()+",'"+sqlDate.toString()+"','"+sqlTime+"')");
          //JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
          //grabar detalle
          String codigo;
           String des;
           String un;
           String cant;
           String pre;
           String total;
          for (int i = 0; i < jTable1.getRowCount(); i++) {
	      //for (int j = 0; j < jTable1.getColumnCount(); j++) {
                   codigo=jTable1.getValueAt(i, 0).toString();
                   des=jTable1.getValueAt(i, 1).toString();
                    un=jTable1.getValueAt(i, 2).toString();
                    cant=jTable1.getValueAt(i, 3).toString();
                    pre=jTable1.getValueAt(i, 4).toString();
                    total=jTable1.getValueAt(i, 5).toString();
		    try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          comando.executeUpdate("insert into detalle_bol(fecha,hora,numero_bol,codigo,descripcion,cant,precio,total) values ('"+sqlDate.toString()+"','"+sqlTime+"',"+String.valueOf(es)+","+codigo+",'"+des+"','"+cant+"','"+pre+"','"+total+"')");
          //JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
		// }
		 // System.out.println();
		}
          
          //fin grabar detalle
          
          //actualizar contador
          try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          comando.executeUpdate("update contador set contador="+String.valueOf(es)+" where documento='BOL'");
          JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
          //fin actualizar contador
        limpiar();
        limpiarjtable(); 
          
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
   difpago();
    }//GEN-LAST:event_jTextField5FocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
   imprimirpdf();   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        buscarcli();
    }//GEN-LAST:event_jTextField7FocusLost

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        limpiar();
        limpiarjtable();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
      private void limpiar(){
        jTextField1.setText(null);
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
     
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
