/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cesion;
import com.itextpdf.text.BaseColor; 
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document; 
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize; 
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase; 
import com.itextpdf.text.pdf.Barcode;
import com.itextpdf.text.pdf.BarcodeEAN; 
import com.itextpdf.text.pdf.PdfContentByte; 
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.*;
import com.itextpdf.text.Paragraph;
import java.io.*; 

import java.util.Calendar;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.*;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintException;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author dev
 */
public class pos extends javax.swing.JFrame {
DefaultTableModel modelo;
DefaultTableModel modelodet;
    /**
     * Creates new form pos
     */
    public pos() {
        initComponents();
        setLocationRelativeTo(null);
        limpiar();
        
        modelo = new DefaultTableModel();
        jTable2.setModel(modelo);
//ableColumnModel columnModel = tabla.getColumnModel();
   
        modelo.addColumn("Id");
        modelo.addColumn("Codigo");
        modelo.addColumn("Productos");
        modelo.addColumn("$ Venta");
        
       TableColumnModel columnModel = jTable2.getColumnModel();
       columnModel.getColumn(0).setWidth(0);
       columnModel.getColumn(0).setMinWidth(0);
       columnModel.getColumn(0).setMaxWidth(0);
       columnModel.getColumn(1).setWidth(0);
       columnModel.getColumn(1).setMinWidth(0);
       columnModel.getColumn(1).setMaxWidth(0);
       columnModel.getColumn(2).setWidth(300); 
        columnModel.getColumn(2).setMinWidth(300);
       columnModel.getColumn(2).setMaxWidth(300);
      
        modelodet = new DefaultTableModel();
        jTable1.setModel(modelodet);
        
       
        modelodet.addColumn("Codigo");
        modelodet.addColumn("Productos");
        modelodet.addColumn("Un");
        modelodet.addColumn("Cantidad");
        modelodet.addColumn("$ Precio");
        modelodet.addColumn("Total");
        
    TableColumnModel columnModel2 = jTable1.getColumnModel();
       columnModel2.getColumn(0).setPreferredWidth(100);
       columnModel2.getColumn(1).setPreferredWidth(300);
       columnModel2.getColumn(2).setPreferredWidth(50); 
       columnModel2.getColumn(3).setPreferredWidth(100);
       columnModel2.getColumn(4).setPreferredWidth(100);
       columnModel2.getColumn(5).setPreferredWidth(100);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Familias = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setTitle("Punto de Venta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane2KeyPressed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Total");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("jTextField4");

        jLabel5.setText("Pago");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("jTextField5");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jLabel6.setText("Vuelto");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("jTextField6");

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("usuario");

        jLabel1.setText("Codigo");

        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jLabel2.setText("Producto");

        jLabel3.setText("Cantidad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cesion/img/DEL.jpg"))); // NOI18N
        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("..");

        jButton3.setText("..");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("..");

        jButton6.setText("Factura FV");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Guia GD");

        jLabel8.setText("Rut");

        jTextField7.setText("jTextField7");
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jLabel9.setText("Razon");

        jTextField8.setText("jTextField8");

        jLabel10.setText("Direccion");

        jTextField9.setText("jTextField9");

        jLabel11.setText("Comuna");

        jTextField10.setText("jTextField10");

        jLabel13.setText("Ciudad");

        jTextField11.setText("jTextField11");

        jLabel14.setText("Giro");

        jTextField12.setText("jTextField12");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cesion/img/ADDREC.jpg"))); // NOI18N
        jButton8.setText("Nuevo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("POS Punto de Venta 2021");

        jLabel15.setText("Fechas");

        jLabel16.setText("jLabel16");

        jLabel17.setText("Boletas Emitidas");

        jLabel18.setText("jLabel18");

        jLabel19.setText("n4@n4.cl");

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setText("Productos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Familias.setBackground(new java.awt.Color(255, 255, 153));
        Familias.setText("Familias");

        jButton10.setText("Cerra Caja");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Boletas");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel7))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))))
                        .addGap(127, 127, 127)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(31, 31, 31)
                        .addComponent(Familias)
                        .addGap(28, 28, 28)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton6)
                        .addGap(28, 28, 28)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(5, 5, 5))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(Familias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton8))
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDriver() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
    }catch(Exception ex) {

    }
  }
    private void limpiarjtable(){
    modelo.setRowCount(0);
    modelodet.setRowCount(0);
   }
    
    public void buscarcli(){
       
       
        String Buscar= jTextField7.getText();
        cargarDriver();
        String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2"; 
        String username ="nelstu"; 
        String password = "armijo183ISLA"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select rut,nombre,direccion,comuna,ciudad,giro from clientes where rut = '"+Buscar+"'"; 
        //  JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
          
        jTextField8.setText(rs.getString(2));
        jTextField9.setText(rs.getString(3)); 
        jTextField10.setText(rs.getString(4)); 
        jTextField11.setText(rs.getString(5)); 
        jTextField12.setText(rs.getString(6));
       
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

    }
    
       public void llenarbarra(){
       
        DefaultTableModel modelodet = (DefaultTableModel)jTable1.getModel();
        String Buscar= jTextField1.getText();
        cargarDriver();
          String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2"; 
        String username ="nelstu"; 
        String password = "armijo183ISLA"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select id,barra,producto,venta2 from productos where barra = '"+Buscar+"'"; 
         // JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
              
              Object []object = new Object[6];
              object[0] = rs.getString(2);
              object[1] = rs.getString(3); 
              object[2] = ""; 
              object[3] = "1"; 
              object[4] = rs.getString(4); 
              object[5] = rs.getString(4); 
              System.out.println("Si" );
              modelodet.addRow(object);
        
          } 
         sumardet();
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

    }
    
    
    
    public void llenar1(){
       
       
        String Buscar= jTextField2.getText();
        cargarDriver();
          String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2"; 
        String username ="nelstu"; 
        String password = "armijo183ISLA"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select id,codigo,producto,venta2 from productos where producto like '%"+Buscar+"%'"; 
         // JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
              
              Object []object = new Object[4];
        object[0] = rs.getString(1);
        object[1] = rs.getString(2); 
        object[2] = rs.getString(3); 
        object[3] = rs.getString(4); 
  System.out.println("Si" );
        
        modelo.addRow(object);
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

    }

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
 DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        // get the selected row index
       int selectedRowIndex = jTable2.getSelectedRow();
        
          Object []object = new Object[6];
        object[0] =  model.getValueAt(selectedRowIndex, 1).toString();
        object[1] =  model.getValueAt(selectedRowIndex, 2).toString();
        object[2] =   "";
        object[3] =  "1";
         object[4] =    model.getValueAt(selectedRowIndex, 3).toString();
          object[5] =    model.getValueAt(selectedRowIndex, 3).toString();
  System.out.println("Si" );
        
        modelodet.addRow(object);
        jTextField2.setText("");
  jTextField1.grabFocus();
  sumardet();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       //  limpiarjtable();
        // TODO add your handling code here:
  llenar1();
  jTextField2.setText("");
  jTextField2.grabFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    void difpago(){
        String cad1=jTextField4.getText().trim();
            String cad2=jTextField5.getText().trim();
            int x1=Integer.parseInt(cad1);
            int x2=Integer.parseInt(cad2);
            int suma=x2-x1;
            String total=String.valueOf(suma);  
            jTextField6.setText(total);
    }
    void sumardet(){
        double sumatoria1=0;
        int totalRow= jTable1.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
             double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,5)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando
             sumatoria1+=sumatoria;
 
          System.out.println(""+sumatoria1);
 
           }
        int numero = (int)sumatoria1;
 jTextField4.setText(String.valueOf((numero)));
}

void imprimirpdf(){
    String pdfFile="C:\\dte3\\doc33.pdf";
    
     Document document = new Document();
      
    try {
        Image imagen = Image.getInstance("pdf417.png");  
      PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(pdfFile));
      document.open();
      PdfContentByte cb = writer.getDirectContent();

      cb.beginText();

      BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
      cb.setFontAndSize(bf, 14);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Empresa", 50, 800, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Direccion", 50, 780, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Comuna", 50, 760, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Ciudad", 50, 740, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "email", 50, 720, 0);
      
       cb.setFontAndSize(bf, 9);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Razon", 50, 680, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Rut", 350, 680, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Direccion", 50, 660, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Fecha", 350, 660, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Comuna", 50, 640, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Forma de Pago", 350, 640, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Ciudad", 50, 620, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Telefono", 50, 600, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "email", 50, 580, 0);
       
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Codigo", 50, 550, 0);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Producto", 100, 550, 0);
         cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Unidad", 250, 550, 0);
          cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "$ Precio", 300, 550, 0);
           cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Cantidad", 400, 550, 0);
            cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Total", 500, 550, 0);
       
       
       
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Subtotal", 400, 180, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Descuento", 400, 160, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Neto", 400, 140, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Iva (19%)", 400, 120, 0);
      cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Total", 400, 100, 0);
     
      
      
       
       
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Timbre Electronico SII", 150, 100, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Resolucion 0 de 2014", 150, 90, 0);
       cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Verifique documento:www.sii.cl", 130, 80, 0);
       cb.setColorFill(BaseColor.RED);
       cb.setFontAndSize(bf, 10);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "SII.-SANTIAGO CENTRO", 430, 700, 0);
         cb.setFontAndSize(bf, 14);
        cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "RUT.:",420, 780, 0);
         cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "FACTURA ELECTRONICA", 400, 760, 0);
          cb.showTextAligned(PdfContentByte.ALIGN_LEFT, "Nª", 450, 740, 0);
      cb.endText();
      
       imagen.setAbsolutePosition(25, 130);
        document.add(imagen);
        
       cb.setRGBColorFill(255, 51, 51);
       cb.setLineWidth(2);
       //x eje y ancho alto
       cb.rectangle(380,710,200,100);
       cb.stroke();
       
       
       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,10,580,820);
       cb.stroke();

       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,540,580,25);
       cb.stroke();
       
       cb.setRGBColorFill(0xFF, 0xFF, 0xFF);
       cb.setLineWidth(1);
       cb.rectangle(10,540,580,150);
       cb.stroke();
   
  

    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
    document.close();
  
    try {
                Desktop.getDesktop().open(new File("C:\\dte3\\doc33.pdf"));
                //To check if the solution is open or not, you can wait some time here
                Thread.sleep(1000);

            } catch (IOException | InterruptedException ex) {
             //   Logger.getLogger(Open.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
 


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(jTable1.getSelectedRow()); 
        sumardet();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        cargarDriver();
          String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2"; 
        String username ="nelstu"; 
        String password = "armijo183ISLA"; 
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        int es=0;
        //buscar numero boleta
      String query1 ="select documento,contador from contador where documento='BOL'"; 
         // JOptionPane.showMessageDialog(null, query);
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query1); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query1);  
           while(rs.next()){ 
              
           
         es = rs.getInt(2)+1;
       
 
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }
    
        //fin buscar numero boleta
        
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);
        //JOptionPane.showMessageDialog(null, "insert into boletas(numero_bol,total,fecha,hora) values ("+String.valueOf(es)+"","+jTextField4.getText()+",'"+sqlDate.toString()+"','"+sqlTime+"')");
          try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          float totalg=Integer.valueOf(jTextField4.getText());
          float neto=Math.round(totalg/1.19);
          float iva=totalg-neto;
          comando.executeUpdate("insert into boletas(estado,numero_bol,total,fecha,hora,neto,iva) values ('VIGENTE',"+String.valueOf(es)+","+jTextField4.getText()+",'"+sqlDate.toString()+"','"+sqlTime+"','"+neto+"','"+iva+"')");
          //JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
          //grabar detalle
          String codigo;
           String des;
           String un;
           String cant;
           String pre;
           String total;
          for (int i = 0; i < jTable1.getRowCount(); i++) {
	      //for (int j = 0; j < jTable1.getColumnCount(); j++) {
                   codigo=jTable1.getValueAt(i, 0).toString();
                   des=jTable1.getValueAt(i, 1).toString();
                    un=jTable1.getValueAt(i, 2).toString();
                    cant=jTable1.getValueAt(i, 3).toString();
                    pre=jTable1.getValueAt(i, 4).toString();
                    total=jTable1.getValueAt(i, 5).toString();
		    try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          comando.executeUpdate("insert into detalle_bol(fecha,hora,numero_bol,codigo,descripcion,cant,precio,total) values ('"+sqlDate.toString()+"','"+sqlTime+"',"+String.valueOf(es)+","+codigo+",'"+des+"','"+cant+"','"+pre+"','"+total+"')");
          //JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
		// }
		 // System.out.println();
		}
          
          //fin grabar detalle
          
          //actualizar contador
          try {
           dbCon = DriverManager.getConnection(dbURL, username, password); 
          Statement comando=dbCon.createStatement();
          comando.executeUpdate("update contador set contador="+String.valueOf(es)+" where documento='BOL'");
          JOptionPane.showMessageDialog(null, "Boleta Creada");
        } catch(SQLException ex){
          setTitle(ex.toString());
        }
          //fin actualizar contador
        limpiar();
        limpiarjtable(); 
        String aimprimir=String.valueOf(es);
    try {
        imprimirtickets(aimprimir);
    } catch (PrintException ex) {
        Logger.getLogger(pos.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(pos.class.getName()).log(Level.SEVERE, null, ex);
    }
          
      jTextField1.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
   difpago();
    }//GEN-LAST:event_jTextField5FocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
   imprimirpdf();   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        buscarcli();
    }//GEN-LAST:event_jTextField7FocusLost

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        limpiar();
        limpiarjtable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
     
                    // TODO add your handling code here:
          // limpiarjtable();
        // TODO add your handling code here:
           llenarbarra();
           jTextField1.setText("");
           jTextField1.grabFocus();
            
      }

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jScrollPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);
        jLabel16.setText(sqlDate.toString());
        
        //consultar Boletas Emitidas
        cargarDriver();
        String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2";
        String username = "nelstu";
        String password = "armijo183ISLA";
        Connection dbCon = null;
        Statement stmt = null;
        ResultSet rs = null;
        String query = "select * from boletas where fecha = '" + sqlDate.toString() + "'";
        // JOptionPane.showMessageDialog(null, query);
        try {
            //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password);
            //getting PreparedStatment to execute query 
            stmt = dbCon.prepareStatement(query);
            //Resultset returned by query 
            rs = stmt.executeQuery(query);
            int son = 0;
            while (rs.next()) {
                son++;

            }
            jLabel18.setText(Integer.toString(son));
        } catch (SQLException ex) {
            System.out.println("Nop");
        }
            jTextField1.grabFocus();
        //fin consultar Boletas Emitidas
    }//GEN-LAST:event_formWindowActivated

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

    posproductos objeto2=new posproductos();
        objeto2.setVisible(true);

      


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        cerrarcaja objeto4=new cerrarcaja();
        objeto4.setVisible(true);
          java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);
        String fe=sqlDate.toString();
        cargarDriver();
        String dbURL = "jdbc:mysql://45.7.230.72:3306/ferreteria2";
        String username = "nelstu";
        String password = "armijo183ISLA";
        Connection dbCon = null;
        Statement stmt = null;
        ResultSet rs = null;
        String query = "select id,caja,fecha,montoinicial,estado from cajas where estado='Abierta' and fecha = '" + fe + "'";
        // JOptionPane.showMessageDialog(null, query);
       String montoinicial="";
        try {
            //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password);
            //getting PreparedStatment to execute query 
            stmt = dbCon.prepareStatement(query);
            //Resultset returned by query 
            rs = stmt.executeQuery(query);
           
            while (rs.next()) {
                 montoinicial=rs.getString("montoinicial");
                 System.out.println("fe->"+montoinicial);
                 objeto4.jLabel2.setText(fe);
                 objeto4.jLabel6.setText(montoinicial);

            }
          
        } catch (SQLException ex) {
            System.out.println("Nop");
        }
        //ventas
          String query1 = "select numero_bol,total,estado,forma from boletas where fecha = '" + fe + "'";
        // JOptionPane.showMessageDialog(null, query);
        int son=0;
        int totalg=0;
        try {
            //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password);
            //getting PreparedStatment to execute query 
            stmt = dbCon.prepareStatement(query1);
            //Resultset returned by query 
            rs = stmt.executeQuery(query1);
         
            while (rs.next()) {
                 totalg=totalg+rs.getInt("total");
                 son++;

            }
          objeto4.jLabel4.setText(String.valueOf(son));
          objeto4.jLabel14.setText(String.valueOf(totalg));
          objeto4.jLabel8.setText(String.valueOf(totalg));
          objeto4.jLabel10.setText("0");
          objeto4.jLabel12.setText("0");
          int tc=parseInt(montoinicial)+totalg;
          objeto4.jLabel16.setText(String.valueOf(tc));
        } catch (SQLException ex) {
            System.out.println("Nop");
        }
        
        //fin ventas
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        boletas objeto9=new boletas();
        objeto9.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    public static void imprimirtickets(String bol) throws PrintException, IOException{
          String url = "jdbc:mysql://45.7.230.72:3306/ferreteria2?useSSL=false";
        String user = "nelstu";
        String password = "armijo183ISLA";
        System.out.println("Buscando Boletas a Imprimir...");
        String query = "SELECT numero_bol,total,fecha,forma,neto,iva FROM boletas WHERE numero_bol="+bol;
        String pr="POS-58";
       //  String pr="PDF Printer";
         int neto=0;
         int iva=0;
       try (Connection con = DriverManager.getConnection(url, user, password);
                PreparedStatement pst = con.prepareStatement(query);
                ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                int  numero=rs.getInt("numero_bol");
                 neto=rs.getInt("neto");
                iva=rs.getInt("iva");
                int  total=rs.getInt("total");
                String fecha=rs.getString("fecha");
                String forma=rs.getString("forma");
                /*
                System.out.print("numero->"+numero);
                System.out.print("neto->"+neto);
                System.out.print("iva->"+iva);
                System.out.print("total->"+total);
                System.out.print("fecha->"+fecha);
                System.out.print("forma->"+forma);
                */
           	PrinterService printerService = new PrinterService();
		
		System.out.println(printerService.getPrinters());
			
		//print some stuff
                printerService.printString(pr, "El WASON BB"+"\n");
                printerService.printString(pr, "Boleta Electronica Numero:"+numero +"\n");
                printerService.printString(pr, "Dennis Joel Hidalgo Jofre \n");
		printerService.printString(pr, "13693753-7 \n");
                printerService.printString(pr, "Minimercado de bebidas Alcoholicas \n");
                printerService.printString(pr, "INTD Fontana 166 \n");
                printerService.printString(pr, "Linares \n");
                printerService.printString(pr, "Fecha:"+fecha+" \n");
                
                printerService.printString(pr, "Codigo Producto  Total \n");
                //detalle
                String query1 = "SELECT numero_bol,descripcion,cant,precio,total,codigo FROM detalle_bol WHERE numero_bol="+bol;
                  try (Connection con1 = DriverManager.getConnection(url, user, password);
                       PreparedStatement pst1 = con.prepareStatement(query1);
                       ResultSet rs1 = pst1.executeQuery()) {

                       while (rs1.next()) {
                         String  codigo=rs1.getString("codigo");
                         String  producto=rs1.getString("descripcion");
                         int  totall=rs1.getInt("total");
                         printerService.printString(pr,codigo+ "\n");
                         printerService.printString(pr,producto +"\n");
                         printerService.printString(pr,"       $"+totall+ "\n");
                       
                         
                    }

        } catch (SQLException ex1) {
                 System.out.println(ex1.getMessage()); 
         
        }
 
                //fin detalle
                printerService.printString(pr, "\nNeto                   $"+neto+" \n");
                printerService.printString(pr, "Iva                    $"+iva+" \n");
                printerService.printString(pr, "Total                  $"+total+" \n");
                
                printerService.printImage(pr);	
                
                printerService.printString(pr, "Timbre Electronico SII Res.85 de 2011 \n");
		// cut that paper!
		byte[] cutP = new byte[] { 0x1d, 'V', 1 };
 
		printerService.printBytes(pr, cutP);
                
                  Connection con3 = null;
                         PreparedStatement ps3 = null;
                         try {
                           con3 = DriverManager.getConnection(url, user, password);
                           String query3 = "update boletas set impresion=? where numero_bol=? ";
                           ps3 = con.prepareStatement(query3);
                           ps3.setString(1, "S");
                           ps3.setInt(2, numero);
                           ps3.executeUpdate();
                           System.out.println("Boleta Actualizada......");
                           } catch (Exception e) {
                             e.printStackTrace();
                             }
                
                
            }

        } catch (SQLException ex) {

         
        }
       
       //update boleta
         System.out.println("Finalizado...");
       //fin update boleta
 
      }
    
    
    
    /**
     * @param args the command line arguments
     */
      private void limpiar(){
        jTextField1.setText(null);
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
     
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Familias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
