/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cesion;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class ventas extends javax.swing.JFrame {
 DefaultTableModel modelo;
    /**
     * Creates new form ventas
     */
    public ventas() {
        initComponents();
        setLocationRelativeTo(null);
           modelo = new DefaultTableModel();
        jTable1.setModel(modelo);
        
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha");
        modelo.addColumn("Numero");
        modelo.addColumn("Rut");
        modelo.addColumn("Cliente");
        modelo.addColumn("Neto");
        modelo.addColumn("Iva");
        modelo.addColumn("Total");
        llenar();
    }

        
    private void limpiarjtable(){
        modelo.setRowCount(0);
   }
    
    
     public void llenar(){
      
        limpiarjtable();
        cargarDriver();
        Conexion cn=new Conexion();
        String dbURL = "jdbc:mysql://"+cn.ip+":3306/"+cn.base;
        String username = cn.usuario;
        String password = cn.pass;
        Connection dbCon = null; 
        Statement stmt = null; 
        ResultSet rs = null; 
        String query ="select id,tipo,fecha,numero,rut,razon,neto,iva,total from documentosncv  "; 
          try {
              //getting database connection to MySQL server 
            dbCon = DriverManager.getConnection(dbURL, username, password); 
           //getting PreparedStatment to execute query 
           stmt = dbCon.prepareStatement(query); 
          //Resultset returned by query 
           rs = stmt.executeQuery(query);  
           while(rs.next()){ 
              
               Object[] object = new Object[9];
               object[0] = rs.getString(1);
               object[1] = rs.getString(2);
               object[2] = rs.getString(3);
               object[3] = rs.getString(4);
               object[4] = rs.getString(5);
               object[5] = rs.getString(6);
               object[6] = rs.getString(7);
               object[7] = rs.getString(8);
               object[8] = rs.getString(9);

 // System.out.println("Si" );
        
           modelo.addRow(object);
          } 
         
        } catch(SQLException ex){
          System.out.println("Nop" ); 
        }

   
          
          
    }
       private void cargarDriver() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
    }catch(Exception ex) {

    }
  }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tipo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NC", "ND", "FV" }));

        jButton1.setText("Buscar");

        jLabel2.setText("Numero");

        jButton2.setText("Generar Nota de Debito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generar Xml y PDF ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // get the selected row index
        int selectedRowIndex = jTable1.getSelectedRow();

    
        // set the selected row data into jtextfields
        jTextField1.setText(model.getValueAt(selectedRowIndex, 0).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        String folio = "1";
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);

        cargarDriver();
        Conexion cn = new Conexion();
        String dbURL = "jdbc:mysql://" + cn.ip + ":3306/" + cn.base;
        String username = cn.usuario;
        String password = cn.pass;
        Connection dbCon = null;
        Connection dbCon0 = null;
        Statement stmt = null;
       String Buscar=this.jTextField1.getText();
            Connection dbCon4 = null;
        Statement stmt4 = null;
        ResultSet rsi = null;
        int es=0;
//if (ticket.equals("S")){
            //buscar numero boleta
            String query1 = "select numero,fecha,rut,razon,neto,iva,total from documentosncv where numero="+Buscar;
            String neto="0";String iva="0";String total="0";String fecha="0";String rut="0";String razon="0";
            
            try {
                //getting database connection to MySQL server 
                dbCon = DriverManager.getConnection(dbURL, username, password);
                //getting PreparedStatment to execute query 
                stmt = dbCon.prepareStatement(query1);
                //Resultset returned by query 
                rsi = stmt.executeQuery(query1);
                while (rsi.next()) {
                    fecha = rsi.getString(2); 
                    rut = rsi.getString(3); 
                    razon = rsi.getString(4); 
                    neto = rsi.getString(5); 
                    iva = rsi.getString(6); 
                    total = rsi.getString(7); 
                    
                     try {
                dbCon = DriverManager.getConnection(dbURL, username, password);
                Statement comando = dbCon.createStatement();
            
                comando.executeUpdate("insert into documentosndv(tpodocref,folioref,codref,razonref,feref,fecha,rut,neto,iva,total,numero) values ('61','"+Buscar+"','1',': Anula Documento Ref.','" + fecha+ "','" + sqlDate.toString()+ "','" + rut+ "'," + neto + "," + iva + "," + total + "," + folio + ")");
                //JOptionPane.showMessageDialog(null, "Boleta Creada");
            } catch (SQLException ex) {
                 System.out.println(ex.getMessage().toString());
            }
                     
                     
                     
                     

                }

            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            
            
            //detalle
            
             String query2 = "select numero,producto,cantidad,precio,total,codigo from detdocumentosncv where numero="+Buscar;
          
            
            try {
                //getting database connection to MySQL server 
                dbCon = DriverManager.getConnection(dbURL, username, password);
                //getting PreparedStatment to execute query 
                stmt = dbCon.prepareStatement(query2);
                //Resultset returned by query 
                rsi = stmt.executeQuery(query2);
                 String descripcion = ""; 
                 String    cant = "";
                 String    precio = ""; 
                 String    totald = ""; 
                 String    codigo= "";
                while (rsi.next()) {
                    descripcion = rsi.getString(2); 
                    cant = rsi.getString(3); 
                    precio = rsi.getString(4); 
                    totald = rsi.getString(5); 
                    codigo= rsi.getString(6); 
                     try {
                dbCon = DriverManager.getConnection(dbURL, username, password);
                Statement comando = dbCon.createStatement();
            
                comando.executeUpdate("insert into detdocumentosndv(numero,codigo,producto,precio,cantidad,total,ide) values (" + folio + "," + codigo + ",'" + descripcion+ "'," + precio + "," + cant+ "," + totald + "," + folio + ")");
                //JOptionPane.showMessageDialog(null, "Boleta Creada");
            } catch (SQLException ex) {
                 System.out.println(ex.getMessage().toString());
            }
                     
                     
                     
                     

                }

            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            
            //fin detalle
            
            JOptionPane.showMessageDialog(null, "Nota de Debito Generada");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

try {
           // TODO add your handling code here:
           Desktop.getDesktop().browse(new URI("http://170.239.87.199/erpexpresspro/masterlibredte/examples/alumgo56brujas.php?folio="+this.jTextField1.getText()));
       } catch (URISyntaxException ex) {
           Logger.getLogger(paneldte.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(paneldte.class.getName()).log(Level.SEVERE, null, ex);
       }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
